<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-13T19:15:58 IST" name="Default suite" finished-at="2023-04-13T19:16:32 IST" duration-ms="34017">
    <groups>
    </groups>
    <test started-at="2023-04-13T19:15:58 IST" name="Default test" finished-at="2023-04-13T19:16:32 IST" duration-ms="34017">
      <class name="com.training.sanity.tests.AlistTest">
        <test-method is-config="true" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.AlistTest@130161f7]" started-at="2023-04-13T19:15:58 IST" name="setUpBeforeClass" finished-at="2023-04-13T19:15:58 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.training.sanity.tests.AlistTest@130161f7]" started-at="2023-04-13T19:15:58 IST" name="setUp" finished-at="2023-04-13T19:16:04 IST" duration-ms="5452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLoginTest()[pri:0, instance:com.training.sanity.tests.AlistTest@130161f7]" started-at="2023-04-13T19:16:04 IST" name="validLoginTest" finished-at="2023-04-13T19:16:13 IST" duration-ms="9349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.training.sanity.tests.AlistTest@130161f7]" started-at="2023-04-13T19:16:13 IST" name="setUp" finished-at="2023-04-13T19:16:18 IST" duration-ms="5100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLoginTest2()[pri:0, instance:com.training.sanity.tests.AlistTest@130161f7]" started-at="2023-04-13T19:16:18 IST" name="validLoginTest2" finished-at="2023-04-13T19:16:32 IST" duration-ms="14031" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Blockbuster Movies] but found [[[ChromeDriver: chrome on WINDOWS (03218169a9314626ea34b393c46b9d27)] -> xpath: //h2[text()='Blockbuster Movies']]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Blockbuster Movies] but found [[[ChromeDriver: chrome on WINDOWS (03218169a9314626ea34b393c46b9d27)] -> xpath: //h2[text()='Blockbuster Movies']]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.training.pom.Blockbust.BlockBuster(Blockbust.java:21)
at com.training.sanity.tests.AlistTest.validLoginTest2(AlistTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest2 -->
      </class> <!-- com.training.sanity.tests.AlistTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
